apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: sxrcu445v-go 
  janus-idp.io/tekton: sxrcu445v-go
  backstage.io/kubernetes-id: sxrcu445v-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: sxrcu445v-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml